version: '2'
services:
  node1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    image: abraham
    container_name: jordan
  node2:
    environment:
      - PEERS=ws://node1:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3002:3001"
    image: issac
    container_name: scottie
    links:
      - abraham:abraham
  node3:
    environment:
      - PEERS=ws://node2:6001
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - "3003:3001"
    image: jacob
    container_name: rodman
    links:
      - issac:issac
